# Generated by Django 4.1.2 on 2022-10-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.CharField(default='Cavtil', max_length=255),
        ),
    ]
